repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-added-large-files
      args: [--maxkb=10240]
    - id: end-of-file-fixer
    - id: mixed-line-ending
