version: "3.8"

services:
  db:
    image: postgres:15
    container_name: infra-db-1
    environment:
      POSTGRES_DB: arescore
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
    networks:
      - db_net

  incident_manager:
    build: ../incident_manager
    container_name: incident_manager
    environment:
      PORT: 8001
    ports:
      - "8001:8001"
    networks:
      - sentinel_net

  sentinelcore-ai:
    build: ../sentinelcore-ai
    container_name: sentinelcore-ai
    environment:
      INCIDENT_MANAGER_URL: http://incident_manager:8001
    ports:
      - "8000:8000"
    depends_on:
      - incident_manager
    networks:
      - sentinel_net

  # Optional: Uncomment and edit for MVP as needed.
  # log_indexer:
  #   build: ../log_indexer
  #   container_name: log_indexer
  #   ports:
  #     - "8002:8002"
  #   networks:
  #     - sentinel_net

volumes:
  db-data:
    driver: local

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true

networks:
  sentinel_net:
  db_net:
