services:
  db:
    image: postgres:15
    container_name: infra-db-1
    environment:
      POSTGRES_DB: arescore
      POSTGRES_USER: ares
      POSTGRES_PASSWORD: arespass
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
