version: "3.8"

services:
  db:
    image: postgres:15
    container_name: infra-db-1
    environment:
      POSTGRES_DB: arescore
      POSTGRES_USER: ares
      POSTGRES_PASSWORD: arespass
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - db_net

  incident_manager:
    build: ../incident_manager
    container_name: incident_manager
    environment:
      PORT: 8001
    ports:
      - "8001:8001"
    networks:
      - sentinel_net

  sentinelcore-ai:
    build: ../sentinelcore-ai
    container_name: sentinelcore-ai
    environment:
      INCIDENT_MANAGER_URL: http://incident_manager:8001
    ports:
      - "8000:8000"
    depends_on:
      - incident_manager
    networks:
      - sentinel_net

  # Optional: Example of a log_indexer service.
  # Uncomment and edit as needed for your MVP.
  # log_indexer:
  #   build: ../log_indexer
  #   container_name: log_indexer
  #   ports:
  #     - "8002:8002"
  #   networks:
  #     - sentinel_net

networks:
  sentinel_net:
  db_net:
