name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show repo/commit
        run: echo "Repo: ${{ github.repository }} @ ${{ github.sha }}"
      - name: Python version
        run: python --version
      - name: Node version
        run: node --version
