name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Prep OS deps (build tools & headers)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential python3-dev pkg-config libffi-dev libssl-dev

      - name: Speed up pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install deps
        run: |
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run tests
        run: pytest -q
