name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        run: |
          echo "Repo: ${{ github.repository }} @ ${{ github.sha }}"
          echo "Runner: $RUNNER_OS"
      - name: Tooling
        run: |
          python --version
          node --version
